### ISSUE TITLE
Does not work with latest Next.js

### ISSUE THREAD

**Issue by raunofreiberg** [uber/react-view#60] opened 2021-02-26 22:15 UTC
Hey 👋 

Trying to set this up for our design system but unfortunately, the simple example from the docs gives me this error:

![image](https://user-images.githubusercontent.com/23662329/109360878-a0015e00-7890-11eb-95f9-e536bb704458.png)

I have a set up a [repo with a minimal example](https://github.com/raunofreiberg/react-view-nextjs) where only `react-view` is installed and Next.js is configured to Webpack 5 (the errors appear on Webpack 4 as well)

I'm kinda lost on this one so help would be appreciated @tajo 🙏 

Thank you

**Comment by tajo** [comment] 2021-02-27 00:13
The repo doesn't have `react-view`. It's an empty scaffold?

**Comment by raunofreiberg** [comment] 2021-02-27 00:35
> The repo doesn't have react-view. It's an empty scaffold?

Oof, I'm sorry. I forgot to commit the changes. Should be working now 🙏

**Comment by raunofreiberg** [comment] 2021-02-27 00:35
I managed to temporarily fix this by deleting `node_modules/react-view/node_modules/semver/*` but not sure what a permanent fix would be.

**Comment by tajo** [comment] 2021-02-28 03:16
Should be fixed with `v2.3.7`. Not sure what the root cause was but bumping deps has helped.

**Closed by tajo** 2021-02-28 03:16 UTC

**Comment by raunofreiberg** [comment] 2021-02-28 09:26
Amazing. Thank you 🙏
